routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('welcome');
Route::post('reservation', 'ReservationController@reserve')->name('reservation.reserve');
Route::post('contact', 'ContactController@sendMessage')->name('contact.send');

Auth::routes();

// Admin Panel
Route::group(['prefix' => 'admin', 'middleware' => 'auth', 'namespace'=>'admin'],
	function(){

		Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard');

		Route::resource('slider', 'SliderController');

		Route::resource('category', 'CategoryController');

		Route::resource('item', 'ItemController');

		// Reservation
		Route::get('reservation', 'ReservationController@index')->name('reservation.index');
		Route::post('reservation/{id}', 'ReservationController@status')->name('reservation.status');
		Route::delete('reservation/{id}', 'ReservationController@destroy')->name('reservation.destroy');

		// Contact
		Route::get('contact', 'ContactController@index')->name('contact.index');
		Route::get('contact/{id}', 'ContactController@show')->name('contact.show');
		Route::delete('contact/{id}', 'ContactController@destroy')->name('contact.destroy');
});

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    protected $fillable = ['name', 'description', 'price', 'image', 'category_id'];


    public function category()
    {
        return $this->belongsTo('App\Category');
    }
}

app/Http/Controllers/Admin/ItemController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Item;
use App\Category;
use Illuminate\Http\Request;
use Brian2694\Toastr\Facades\Toastr;
use App\Http\Controllers\Controller;

class ItemController extends Controller
{

    public function index()
    {
        $items = Item::all();
        return view('admin.item.index', compact('items'));
    }


    public function create()
    {
        $categories = Category::all();
        return view('admin.item.create', compact('categories'));
    }


    public function store(Request $request)
    {
        $data = $request->all();
        $this->validate($request, [
            'category_id' =>'required|max:50|string',
            'name' =>'required|max:50|string',
            'description' =>'required|max:120|string',
            'price' =>'required|numeric',
            'image' => 'required|mimes:jpeg,png,jpg'
        ]);
        $image = $request->file('image');
        $slug = str_slug('$request', 'name');
        if(isset($image)) {
            $CurrentDate = now()->toDateString();
            $imagename = $slug.'-'. $CurrentDate.'-'.uniqid().'.'.$image->getClientOriginalExtension();
            if(!file_exists('uploads/slider'))
            {
                mkdir('uploads/item', 0777, true);
            }
            if (!$image->move(public_path('/uploads/item'), $imagename)) {
                return redirect()->back()
                    ->with('error', 'The image is not moved into folder.');
            }
        } else
        {
            $imagename = 'default.png';
        }
        $data['image'] = $imagename;
        $item = Item::create($data);
        if($item) {
            return redirect()->route('item.index')->with('successMsg', 'Item Successfully Saved.');
        } else {
            return redirect()->route('item.index')->with('error', 'Item Does Not Saved.');
        }

    }


    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        $item = Item::find($id);
        if($item){
            $categories = Category::all();
            return view('admin.item.edit', compact('item', 'categories'));
        }else {
            return 'Error';
        }
    }


    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'category' =>'required|max:50|string',
            'name' =>'required|max:50|string',
            'description' =>'required|max:120|string',
            'price' =>'required|numeric',
            'image' => 'mimes:jpeg,png,jpg'
        ]);

        $item = Item::find($id);
        if($item){
            $image = $request->file('image');
            $slug = str_slug('$request','name');
            $item = Item::find($id);
            if (isset($image)) {
                $CurrentDate = now()->toDateString();
                $imagename = $slug.'-'. $CurrentDate.'-'.uniqid().'.'.$image->getClientOriginalExtension();
                if(!file_exists('uploads/item'))
                {
                    unlink('uploads/item/'.$item->image);
                    mkdir('uploads/item', 0777, true);
                }

                if (!$image->move(public_path('/uploads/item'), $imagename)) {
                    return redirect()->back()
                        ->with('error', 'The image is not moved into folder.');
                }
            } else {
                $imagename = $item->image;
            }

            $item->category_id = $request->category;
            $item->name = $request->name;
            $item->description = $request->description;
            $item->price = $request->price;
            $item->image = $imagename;
            $item->update();
            return redirect()->route('item.index')->with('successMsg', 'Item Successfully Updated.');
        }else {
            return redirect()->route('item.index')->with('errorMsg', 'ID you are looking for is not found.');
        }

    }


    public function destroy($id)
    {
        $item = Item::find($id);

        if ($item) {
            if (file_exists('uploads/item/'.$item->image)){
                unlink('uploads/item/'.$item->image);
            }
            $delete = $item->delete();

            if ($delete) {
                Toastr::success('Reservation deleted successfully', 'Message', ["positionClass" => "toast-top-right"]);

                return response([
                    'status' => true
                ], 200);
            } else {
                Toastr::error('Item you are looking for is not.', 'Error', ["positionClass" => "toast-top-right"]);

                return response([
                    'status' => false
                ], 404);
            }
        } else {
            Toastr::error('Items you are looking for is not found.', 'Error', ["positionClass" => "toast-top-right"]);
            return response([
                'status' => false
            ], 404);
        }

    }

}

resources/views/admin/item/create.blade.php
@extends('layouts.app')

@section('title', 'Item')

@push('css')

@endpush

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    @if($errors->any())
                                @foreach($errors->all() as $error)
                                    <div class="alert alert-danger">
                                        <button type="button" aria-hidden="true" class="close" onclick="this.parentElement.style.display='none'">&times;</button>
                                        <span>{{ $error }} </span>
                                    </div>
                                @endforeach
                     @endif
                    <div class="card">
                        <div class="card-header" data-background-color="purple">
                            <h4 class="title">Add New Item</h4>

                        </div>
                        <div class="card-content">
                            <form method="POST" action="{{ route('item.store') }}" enctype="multipart/form-data">
                                @csrf
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group label-floating">
                                            <label class="control-label" for="category-name">Category Name</label>
                                           <select class="form-control" name="category_id" id="category-name">
                                               @foreach($categories as $category)
                                                   <option value="{{ $category->id }}">{{ $category->name }}</option>
                                               @endforeach
                                           </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group label-floating">
                                            <label class="control-label" for="name">Name</label>
                                            <input type="text" class="form-control" name="name" value="{{ old('name') }}" id="name">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group label-floating">
                                            <label class="control-label" for="description">Description</label>
                                            <textarea  class="form-control" id="description" name="description">{{ old('description') }}</textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group label-floating">
                                            <label class="control-label" for="price">Price</label>
                                            <input type="number" id="price" class="form-control" name="price" value="{{ old('price') }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                            <label class="control-label" for="image">Image</label>
                                            <input type="file"  name="image" id="image">
                                    </div>
                                </div>
                                <a href="{{ route('item.index') }}" class="btn btn-danger">Back</a>
                                <button class="btn btn-primary" type="submit">Save</button>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

@endsection

@push('scripts')
    <script>
        window.setTimeout(function() {
            $(".alert").fadeTo(500, 0).slideUp(500, function(){
              $(this).remove();
             });
        }, 800);
    </script>

@endpush

resources/views/admin/item/edit.blade.php
@extends('layouts.app')

@section('title', 'Item')

@push('css')

@endpush

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    @if($errors->any())
                        @foreach($errors->all() as $error)
                            <div class="alert alert-danger">
                                <button type="button" aria-hidden="true" class="close" onclick="this.parentElement.style.display='none'">&times;</button>
                                        <span>{{ $error }} </span>
                            </div>
                        @endforeach
                    @endif
                    <div class="card">
                        <div class="card-header" data-background-color="purple">
                            <h4 class="title">Update Item</h4>

                        </div>
                        <div class="card-content">
                            <form method="POST" action="{{ route('item.update', $item->id) }}" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group label-floating">
                                            <label class="control-label">Category Name</label>
                                            <select class="form-control" name="category">
                                                @foreach($categories as $category)
                                                    <option {{ $category->id == $item->category->id ? 'selected' : '' }} value="{{ $category->id }}">{{ $category->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group label-floating">
                                            <label class="control-label" for="name">Name</label>
                                            <input type="text" class="form-control" id="name" value="{{ $item->name }}" name="name" />
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group label-floating">
                                            <label class="control-label" for="description">Description</label>
                                            <textarea  class="form-control" name="description" id="description">{{ $item->description }}</textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group label-floating">
                                            <label class="control-label" for="price">Price</label>
                                            <input type="number" class="form-control" name="price" value="{{ $item->price }}" id="price">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <label class="control-label" for="image">Image</label>
                                        <input type="file"  name="image" id="image">
                                        <img src="{{ asset('uploads/item/'.$item->image) }}" style="width:250px;" alt="slider image">
                                    </div>
                                </div>
                                <a href="{{ route('item.index') }}" class="btn btn-danger">Back</a>
                                <button class="btn btn-primary" type="submit">Save</button>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

@endsection

@push('scripts')
    <script>
        window.setTimeout(function() {
            $(".alert").fadeTo(500, 0).slideUp(500, function(){
                $(this).remove();
            });
        }, 800);
    </script>

@endpush

resources/views/admin/item/index.blade.php
@extends('layouts.app')

@section('title', 'Items')

@push('css')
   <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css">
@endpush

@section('content')
   <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            @if(session('successMsg'))
                                <div class="alert alert-success">
                                    <button type="button" aria-hidden="true" class="close" onclick="this.parentElement.style.display='none'">&times;</button>
                                        <strong>{{ session('successMsg') }} </strong>
                                </div>
                             @endif
                            <a href="{{ route('item.create') }}" class="btn btn-info">Add New</a>
                            <div class="card">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">All Categories</h4>
                                
                                </div>
                                <div class="card-content table-responsive">
                                    <table id="table" class="table table-striped table-bordered" cellspacing="0" width="100%">
                                        <thead class="text-primary">
                                            <tr>
                                                <th>ID</th>
                                                <th>Name</th>
                                                <th>Image</th>
                                                <th>Category Name</th>
                                                <th>Description</th>
                                                <th>Price</th>
                                                <th>Created At</th>
                                                <th>Updated At</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($items as $key=>$item)
                                                <tr data-id="{{ $item->id }}">
                                                    <td>{{ $key + 1 }}</td>
                                                    <td>{{ $item->name }}</td>
                                                    <td style="width:30%"><img class="img-responsive img-thumbnail" id="item-image" src="{{ asset('uploads/item/'.$item->image) }}" alt="image" style="width:300px;margin-left:80px;"></td>
                                                    <td>{{ $item->category->name}}</td>
                                                    <td>{{ $item->description }}</td>
                                                    <td>{{ $item->price }}</td>
                                                    <td>{{ $item->created_at }}</td>
                                                    <td>{{ $item->updated_at }}</td>
                                                    <td>
                                                        <a href="{{ route('item.edit', $item->id) }}" class="btn btn-info btn-sm"><i class="material-icons">mode_edit</i></a>
                                                        <button type="button" class="btn btn-danger btn-sm delete-btn" data-id="{{$item->id}}"><i class="material-icons">delete</i></button>

                                                    </td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                    </div>
                        
                </div>
         </div>
   </div>
    @include('modals.confirm')
@endsection

@push('scripts') 
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="{{ asset('backend/js/modal.js') }}" type="text/javascript"></script>
    <script>
        window.setTimeout(function() {
            $(".alert").fadeTo(500, 0).slideUp(500, function(){
                $(this).remove();
            });
        }, 800);
    </script>
@endpush