routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('welcome');
Route::post('reservation', 'ReservationController@reserve')->name('reservation.reserve');
Route::post('contact', 'ContactController@sendMessage')->name('contact.send');

Auth::routes();

// Admin Panel
Route::group(['prefix' => 'admin', 'middleware' => 'auth', 'namespace'=>'admin'],
	function(){

		Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard');

		Route::resource('slider', 'SliderController');

		Route::resource('category', 'CategoryController');

		Route::resource('item', 'ItemController');

		// Reservation
		Route::get('reservation', 'ReservationController@index')->name('reservation.index');
		Route::post('reservation/{id}', 'ReservationController@status')->name('reservation.status');
		Route::delete('reservation/{id}', 'ReservationController@destroy')->name('reservation.destroy');

		// Contact
		Route::get('contact', 'ContactController@index')->name('contact.index');
		Route::get('contact/{id}', 'ContactController@show')->name('contact.show');
		Route::delete('contact/{id}', 'ContactController@destroy')->name('contact.destroy');
});

resources/views/layouts/partial/footer.blade.php
<footer class="footer" style="position:fixed; bottom:0; width:100%; background-color:#eee;">
                <div class="container-fluid" style="width:700px; margin:0 auto;">
                    <nav class="pull-left">
                        <ul>
                            <li>
                                <a href="#">
                                    Home
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Company
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Portfolio
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Blog
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <p class="copyright pull-left">
                        &copy;
                        <script>
                            document.write(new Date().getFullYear())
                        </script>
                        <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
                    </p>
                </div>
            </footer>

resources/views/layouts/partial/sidebar.blade.php
 <div class="sidebar" data-color="purple" data-image="{{ asset('backend/img/sidebar-1.jpg') }}">
            <div class="logo">
                <a href="{{ route('admin.dashboard') }}" class="simple-text">
                    Mamma's Kitchen
                </a>
            </div>
            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li class="{{ Request::is('admin/dashboard*') ? 'active': '' }}">
                        <a href="{{ route('admin.dashboard') }}">
                            <i class="material-icons">dashboard</i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                    <li class="{{ Request::is('admin/slider*') ? 'active': '' }}">
                        <a href="{{ route('slider.index')  }}">
                            <i class="material-icons">slideshow</i>
                            <p>Sliders</p>
                        </a>
                    </li>
                    <li class="{{ Request::is('admin/category*') ? 'active': '' }}">
                        <a href="{{ route('category.index')  }}">
                            <i class="material-icons">content_paste</i>
                            <p>Categories</p>
                        </a>
                    </li>
                    <li class="{{ Request::is('admin/item*') ? 'active': '' }}">
                        <a href="{{ route('item.index')  }}">
                            <i class="material-icons">library_books</i>
                            <p>Items</p>
                        </a>
                    </li>
                    <li class="{{ Request::is('admin/reservation*') ? 'active': '' }}">
                        <a href="{{ route('reservation.index')  }}">
                            <i class="material-icons">chrome_reader_mode</i>
                            <p>Reservations</p>
                        </a>
                    </li>
                    <li class="{{ Request::is('admin/contact*') ? 'active': '' }}">
                        <a href="{{ route('contact.index')  }}">
                            <i class="material-icons">message</i>
                            <p>Contact Messages</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

resources/views/layouts/partial/topbar.blade.php
<nav class="navbar navbar-transparent navbar-absolute">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#"> Material Dashboard </a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="material-icons">dashboard</i>
                                    <p class="hidden-lg hidden-md">Dashboard</p>
                                </a>
                            </li>
                            
                            <li>
                                <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="material-icons">person</i>
                                    <p class="hidden-lg hidden-md">Profile</p>
                                </a>
                            </li>
                            <li>
                                <div class="dropdown">
                                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                        <i class="material-icons">exit_to_app</i>
                                        <p class="hidden-lg hidden-md">Logout</p>
                                    </button>
                                    <div class="dropdown-menu">
                                        <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                                            <i class="material-icons">exit_to_app</i>
                                            <span>Logout</span>
                                        </a>
                                    </div>
                                </div>

                                <form method='POST' action="{{ route('logout') }}" id='logout-form'>
                                    @csrf
                                @csrf
                      @csrf
                      @csrf
                      </form>
                            </li>
                        </ul>
                        
                    </div>
                </div>
            </nav>