routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('welcome');
Route::post('reservation', 'ReservationController@reserve')->name('reservation.reserve');
Route::post('contact', 'ContactController@sendMessage')->name('contact.send');

Auth::routes();

// Admin Panel
Route::group(['prefix' => 'admin', 'middleware' => 'auth', 'namespace'=>'admin'],
	function(){

		Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard');

		Route::resource('slider', 'SliderController');

		Route::resource('category', 'CategoryController');

		Route::resource('item', 'ItemController');

		// Reservation
		Route::get('reservation', 'ReservationController@index')->name('reservation.index');
		Route::post('reservation/{id}', 'ReservationController@status')->name('reservation.status');
		Route::delete('reservation/{id}', 'ReservationController@destroy')->name('reservation.destroy');

		// Contact
		Route::get('contact', 'ContactController@index')->name('contact.index');
		Route::get('contact/{id}', 'ContactController@show')->name('contact.show');
		Route::delete('contact/{id}', 'ContactController@destroy')->name('contact.destroy');
});

app/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    protected $fillable = ['title', 'sub_title', 'image'];
}

app/Http/Controllers/Admin/SliderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Slider;
use Illuminate\Http\Request;
use Brian2694\Toastr\Facades\Toastr;
use App\Http\Controllers\Controller;

class SliderController extends Controller
{

    public function index()
    {
        $sliders = Slider::all();
        return view('admin.slider.index', compact('sliders'));
    }


    public function create()
    {
        return view('admin.slider.create');
    }


    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|max:50|string',
            'sub_title' => 'required|max:50|string',
            'image' => 'required|mimes:jpeg,png,jpg'
        ]);

        $data = $request->all();
        $image = $request->file('image');
        $slug = str_slug('$request', 'title');
        if (isset($image)) {
            $CurrentDate = now()->toDateString();
            $image_name = $slug . '-' . $CurrentDate . '-' . uniqid() . '.' . $image->getClientOriginalExtension();
            if (!file_exists('uploads/slider')) {
                mkdir('uploads/slider', 0777, true);
            }
            if (!$image->move(public_path('/uploads/slider'), $image_name)) {
                return redirect()->back()
                    ->with('error', 'The image is not moved into folder.');
            }
        } else {
            $image_name = 'default.png';
        }

        $data['image'] = $image_name;
        $slider = Slider::create($data);
        if ($slider) {
            return redirect()->route('slider.index')->with('successMsg', 'Slider Successfully Saved.');
        } else {
            return redirect()->route('slider.index')->with('errorMsg', 'Slider Does Not Saved.');
        }

    }

    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        $slider = Slider::find($id);
        if($slider) {
            return view('admin.slider.edit', compact('slider'));
        }else {
            return 'Error';
        }

    }


    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required|max:50|string',
            'sub_title' => 'required|max:50|string',
            'image' => 'mimes:jpeg,png,jpg'
        ]);

        $image = $request->file('image');
        $slug = str_slug('$request', 'title');
        $slider = Slider::find($id);
        if (isset($image)) {
            $CurrentDate = now()->toDateString();
            $imagename = $slug . '-' . $CurrentDate . '-' . uniqid() . '.' . $image->getClientOriginalExtension();
            if (!file_exists('uploads/slider')) {
                mkdir('uploads/slider', 0777, true);
            }

            if (!$image->move(public_path('/uploads/slider'), $imagename)) {
                return redirect()->back()
                    ->with('error', 'The image is not moved into folder.');
            }
        } else {
            $imagename = $slider->image;
        }

        $slider->title = $request->title;
        $slider->sub_title = $request->sub_title;
        $slider->image = $imagename;
        $slider->update();
        if($slider) {
            return redirect()->route('slider.index')->with('successMsg', 'Slider Successfully Updated.');
        }
            return redirect()->route('slider.index')->with('errorMsg', 'Slider Does Not Updated.');
    }


    public function destroy($id)
    {
        $slider = Slider::find($id);

        if ($slider) {
            unlink('uploads/slider/' . $slider->image);
            $delete = $slider->delete();

            if ($delete) {
                Toastr::success('Reservation deleted successfully', 'Message', ["positionClass" => "toast-top-right"]);

                return response([
                    'status' => true
                ], 200);
            } else {
                Toastr::error('ID you are looking for is not found.', 'Error', ["positionClass" => "toast-top-right"]);

                return response([
                    'status' => false
                ], 404);
            }
        } else {
            Toastr::error('ID you are looking for is not found.', 'Error', ["positionClass" => "toast-top-right"]);

            return response([
                'status' => false
            ], 404);
        }

    }



}

resources/views/admin/slider/create.blade.php
@extends('layouts.app')

@section('title', 'Slider')

@push('css')

@endpush

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    @if($errors->any())
                                @foreach($errors->all() as $error)
                                    <div class="alert alert-danger">
                                        <button type="button" aria-hidden="true" class="close" onclick="this.parentElement.style.display='none'">&times;</button>
                                        <span> {{ $error }} </span>
                                    </div>
                                @endforeach
                     @endif
                    <div class="card">
                        <div class="card-header" data-background-color="purple">
                            <h4 class="title">Add New Slider</h4>

                        </div>
                        <div class="card-content">
                            <form method="POST" action="{{ route('slider.store') }}" enctype="multipart/form-data">
                                @csrf
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group label-floating">
                                            <label class="control-label" for="title">Title</label>
                                            <input type="text" class="form-control" name="title" value="{{ old('title') }}" id="title">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group label-floating">
                                            <label class="control-label" for="sub-title">Sub Title</label>
                                            <input type="text" class="form-control" name="sub_title" value="{{ old('sub_title') }}" id="sub-title">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                            <label class="control-label" for="image">Image</label>
                                            <input type="file"  name="image" id="image">
                                    </div>
                                </div>
                                <a href="{{ route('slider.index') }}" class="btn btn-danger">Back</a>
                                <button class="btn btn-primary" type="submit">Save</button>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

@endsection

@push('scripts')
    <script>
         window.setTimeout(function() {
            $(".alert").fadeTo(500, 0).slideUp(500, function(){
              $(this).remove();
             });
         }, 800);
    </script>

@endpush

resources/views/admin/slider/edit.blade.php
@extends('layouts.app')

@section('title', 'Slider')

@push('css')

@endpush

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    @if($errors->any())
                        @foreach($errors->all() as $error)
                            <div class="alert alert-danger">
                                <button type="button" aria-hidden="true" class="close" onclick="this.parentElement.style.display='none'">&times;</button>
                                        <span>  {{ $error }} </span>
                            </div>
                        @endforeach
                    @endif
                    <div class="card">
                        <div class="card-header" data-background-color="purple">
                            <h4 class="title">Update Slider</h4>

                        </div>
                        <div class="card-content">
                            <form method="POST" action="{{ route('slider.update', $slider->id) }}" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group label-floating">
                                            <label class="control-label" for="title">Title</label>
                                            <input type="text" class="form-control" name="title" value="{{ $slider->title }}" id="title">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group label-floating">
                                            <label class="control-label" for="sub-title">Sub Title</label>
                                            <input type="text" class="form-control" name="sub_title" value="{{ $slider->sub_title }}" id="sub-title">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <label class="control-label" for="image">Image</label>
                                        <input type="file"  name="image" id="image">
                                        <img src="{{ asset('uploads/slider/'.$slider->image) }}" alt="slider image" style="width:250px;">
                                    </div>
                                </div>
                                <a href="{{ route('slider.index') }}" class="btn btn-danger">Back</a>
                                <button class="btn btn-primary" type="submit">Save</button>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

@endsection

@push('scripts')
    <script>
         window.setTimeout(function() {
             $(".alert").fadeTo(500, 0).slideUp(500, function(){
                $(this).remove();
             });
         }, 800);
    </script>

@endpush

resources/views/admin/slider/index.blade.php
@extends('layouts.app')

@section('title', 'Slider')

@push('css')
   <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css">
@endpush

@section('content')
   <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    @if(session('successMsg'))
                        <div class="alert alert-success">
                            <button type="button" aria-hidden="true" class="close" onclick="this.parentElement.style.display='none'">&times;</button>
                                <span> {{ session('successMsg') }} </span>
                        </div>
                     @endif
                    <a href="{{ route('slider.create') }}" class="btn btn-info">Add New</a>
                    <div class="card">
                        <div class="card-header" data-background-color="purple">
                            <h4 class="title">All Slider</h4>

                        </div>
                        <div class="card-content table-responsive">
                            <table id="table" class="table table-striped table-bordered" cellspacing="0" width="100%">
                                <thead class="text-primary">
                                    <tr>
                                        <th>ID</th>
                                        <th>Title</th>
                                        <th>Sub Title</th>
                                        <th>Image</th>
                                        <th>Created At</th>
                                        <th>Updated At</th>
                                        <th>Action</th>
                                     </tr>
                                </thead>
                                <tbody>
                                    @foreach($sliders as $key=>$slider)
                                        <tr data-id="{{ $slider->id }}">
                                            <td>{{ $key + 1 }}</td>
                                            <td>{{ $slider->title }}</td>
                                            <td>{{ $slider->sub_title }}</td>
                                            <td>{{ $slider->image }}</td>
                                            <td>{{ $slider->created_at }}</td>
                                            <td>{{ $slider->updated_at }}</td>
                                            <td>
                                                <a href="{{ route('slider.edit', $slider->id) }}" class="btn btn-info btn-sm"><i class="material-icons">mode_edit</i></a>

                                                <form method='POST' id="form-delete-{{ $slider->id }}" action="{{ route('slider.destroy', $slider->id) }}" style="display:none;">
                                                    @csrf
                                                    @method('DELETE')
                                                </form>
                                                <button type="button" class="btn btn-danger btn-sm delete-btn" data-id="{{ $slider->id }}"><i class="material-icons">delete</i></button>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
   </div>
   @include('modals.confirm')
@endsection


@push('scripts') 
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="{{ asset('backend/js/modal.js') }}" type="text/javascript"></script>
    <script>
        window.setTimeout(function() {
            $(".alert").fadeTo(500, 0).slideUp(500, function(){
             $(this).remove();
            });
        }, 800);
    </script>

@endpush